In [1]:
import pandas as pd

from sklearn.model_selection import train_test_split

ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

In [7]:
df = pd.read_csv('500hits.csv', encoding='latin-1')

In [8]:

df.head()

,PLAYER,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA,HOF
0,Ty Cobb,24,3035,11434,2246,4189,724,295,117,726,1249,357,892,178,0.366,1
1,Stan Musial,22,3026,10972,1949,3630,725,177,475,1951,1599,696,78,31,0.331,1
2,Tris Speaker,22,2789,10195,1882,3514,792,222,117,724,1381,220,432,129,0.345,1
3,Derek Jeter,20,2747,11195,1923,3465,544,66,260,1311,1082,1840,358,97,0.310,1
4,Honus Wagner,21,2792,10430,1736,3430,640,252,101,0,963,327,722,15,0.329,1

In [9]:
# split data
X = df.drop(columns=['PLAYER', 'HOF'])
y = df['HOF']

In [10]:
X.head()

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA
0,24,3035,11434,2246,4189,724,295,117,726,1249,357,892,178,0.366
1,22,3026,10972,1949,3630,725,177,475,1951,1599,696,78,31,0.331
2,22,2789,10195,1882,3514,792,222,117,724,1381,220,432,129,0.345
3,20,2747,11195,1923,3465,544,66,260,1311,1082,1840,358,97,0.310
4,21,2792,10430,1736,3430,640,252,101,0,963,327,722,15,0.329

In [11]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: HOF, dtype: int64

In [12]:
X.shape

(465, 14)

In [13]:
y.shape

(465,)

In [14]:
# train and test
# test size is usually 20% or 30% or 35%
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=11, test_size=0.2)

In [15]:
X_train.shape

(372, 14)

In [16]:
X_test.shape

(93, 14)

In [17]:
y_train.shape

(372,)

In [18]:
y_test.shape

(93,)

In [19]:
X_train.head()

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA
289,18,2028,7298,873,1993,284,40,325,1163,620,1313,20,38,0.273
288,13,1836,6826,856,1996,392,117,43,402,513,360,247,108,0.292
350,14,1799,6373,876,1854,282,64,49,630,844,627,37,51,0.291
196,17,2158,7911,1057,2276,414,92,94,844,690,784,246,138,0.288
184,19,2390,8570,1386,2369,420,65,244,1084,1197,1099,143,75,0.276

In [21]:
X_train.describe().round(3)

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA
count,372.000,372.000,372.000,372.000,372.000,372.000,372.000,372.000,372.000,372.000,372.000,372.000,372.000,372.000
mean,17.011,2046.522,7526.078,1154.126,2177.995,382.505,78.094,202.642,901.073,780.105,850.323,196.927,58.987,0.289
std,2.662,351.233,1302.406,291.308,426.615,97.173,48.798,141.726,484.370,327.453,472.918,185.586,49.322,0.021
min,11.000,1331.000,4981.000,651.000,1660.000,177.000,3.000,9.000,0.000,239.000,0.000,7.000,0.000,0.246
25%,15.000,1797.500,6507.500,936.000,1838.000,312.000,41.000,79.750,645.000,536.500,448.000,64.500,23.000,0.274
50%,17.000,1992.000,7237.000,1099.000,2080.500,367.000,67.000,185.500,977.500,719.000,844.000,141.000,52.000,0.288
75%,19.000,2245.500,8198.250,1305.000,2383.750,436.250,108.000,293.250,1218.500,961.250,1234.250,285.500,84.000,0.300
max,26.000,3308.000,12364.000,2295.000,4189.000,792.000,309.000,755.000,2297.000,2190.000,1936.000,1406.000,335.000,0.366

In [22]:
X_test.describe()

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA
count,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000
mean,17.204301,2057.408602,7452.967742,1135.064516,2139.258065,374.741935,80.397849,194.677419,867.010753,797.387097,836.064516,191.817204,54.473118,0.286903
std,3.153877,368.580421,1265.371087,283.877148,415.164868,93.929310,51.791837,151.599814,495.127070,328.754568,552.308905,166.925976,42.508462,0.021776
min,11.000000,1399.000000,5472.000000,601.000000,1660.000000,206.000000,14.000000,15.000000,0.000000,266.000000,15.000000,8.000000,0.000000,0.248000
25%,15.000000,1820.000000,6622.000000,935.000000,1818.000000,310.000000,45.000000,78.000000,618.000000,527.000000,359.000000,61.000000,15.000000,0.272000
50%,17.000000,1997.000000,7359.000000,1108.000000,2054.000000,361.000000,68.000000,151.000000,926.000000,750.000000,745.000000,137.000000,50.000000,0.285000
75%,19.000000,2282.000000,8096.000000,1283.000000,2256.000000,432.000000,99.000000,291.000000,1138.000000,937.000000,1179.000000,271.000000,83.000000,0.299000
max,25.000000,2850.000000,10876.000000,1859.000000,3430.000000,668.000000,252.000000,612.000000,1922.000000,1747.000000,2597.000000,744.000000,173.000000,0.340000

- Normalization: numbers of 0 to 1, range of 0 to 1

(X - Min(X)) / (Max(X) - Min(X))

- Standardization: mean of 0 and std of 1, normal distribution
can have negatives and positives, can have large numbers, preferred when have outliers

(X - Mean(X)) / Std

In [8]:
df = df.drop(columns=['PLAYER', 'CS'])

In [9]:
df.head()

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,BA,HOF
0,24,3035,11434,2246,4189,724,295,117,726,1249,357,892,0.366,1
1,22,3026,10972,1949,3630,725,177,475,1951,1599,696,78,0.331,1
2,22,2789,10195,1882,3514,792,222,117,724,1381,220,432,0.345,1
3,20,2747,11195,1923,3465,544,66,260,1311,1082,1840,358,0.310,1
4,21,2792,10430,1736,3430,640,252,101,0,963,327,722,0.329,1

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 465 entries, 0 to 464
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   YRS     465 non-null    int64
 1   G       465 non-null    int64
 2   AB      465 non-null    int64
 3   R       465 non-null    int64
 4   H       465 non-null    int64
 5   2B      465 non-null    int64
 6   3B      465 non-null    int64
 7   HR      465 non-null    int64
 8   RBI     465 non-null    int64
 9   BB      465 non-null    int64
 10  SO      465 non-null    int64
 11  SB      465 non-null    int64
 12  BA      465 non-null    float64
 13  HOF     465 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 51.0 KB

In [11]:
df.describe().round(3)

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,BA,HOF
count,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000
mean,17.049,2048.699,7511.456,1150.314,2170.247,380.953,78.555,201.049,894.260,783.561,847.471,195.905,0.289,0.329
std,2.765,354.392,1294.066,289.635,424.191,96.483,49.363,143.623,486.193,327.432,489.224,181.846,0.021,0.475
min,11.000,1331.000,4981.000,601.000,1660.000,177.000,3.000,9.000,0.000,239.000,0.000,7.000,0.246,0.000
25%,15.000,1802.000,6523.000,936.000,1838.000,312.000,41.000,79.000,640.000,535.000,436.000,63.000,0.273,0.000
50%,17.000,1993.000,7241.000,1104.000,2076.000,366.000,67.000,178.000,968.000,736.000,825.000,137.000,0.287,0.000
75%,19.000,2247.000,8180.000,1296.000,2375.000,436.000,107.000,292.000,1206.000,955.000,1226.000,285.000,0.300,1.000
max,26.000,3308.000,12364.000,2295.000,4189.000,792.000,309.000,755.000,2297.000,2190.000,2597.000,1406.000,0.366,2.000

In [12]:
X1 = df.iloc[:, 0:13]

In [13]:
X2 = df.iloc[:, 0:13]

In [15]:
# standardization
from sklearn.preprocessing import StandardScaler

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/utils/_param_validation.py:11: UserWarning: A NumPy version >=1.23.5 and <2.3.0 is required for this version of SciPy (detected version 1.23.2)
  from scipy.sparse import csr_matrix, issparse

TypeError: